-- Structure only. Generated by tools/legacy/Export-LegacyPackage.ps1
-- No INSERT statement can reach this file: it is written by a
-- different branch of the parser than the one that sees INSERTs.

-- phpMyAdmin SQL Dump
-- version 5.2.2
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Sep 23, 2025 at 03:00 PM
-- Server version: 10.6.23-MariaDB-log
-- PHP Version: 8.3.25
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
--
-- Database: `fabrizia_fashion`
--
-- --------------------------------------------------------
--
-- Table structure for table `address`
--
CREATE TABLE `address` (
  `id` int(12) NOT NULL,
  `municipality` varchar(255) NOT NULL,
  `user_id` int(12) NOT NULL,
  `city` varchar(255) NOT NULL,
  `address` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `address`
--
-- --------------------------------------------------------
--
-- Table structure for table `admin_users`
--
CREATE TABLE `admin_users` (
  `id` int(3) NOT NULL,
  `username` varchar(255) NOT NULL,
  `real_name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(32) NOT NULL,
  `trn_date` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `admin_users`
--
-- --------------------------------------------------------
--
-- Table structure for table `attributes`
--
CREATE TABLE `attributes` (
  `id` int(6) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `type` varchar(32) NOT NULL,
  `special` int(2) NOT NULL DEFAULT 0,
  `deleted` int(2) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `attributes`
--
-- --------------------------------------------------------
--
-- Table structure for table `attr_values`
--
CREATE TABLE `attr_values` (
  `id` int(12) NOT NULL,
  `attr_id` int(12) NOT NULL,
  `value` int(4) NOT NULL,
  `text` varchar(255) NOT NULL,
  `image` varchar(32) DEFAULT NULL,
  `order` int(10) NOT NULL,
  `visible` int(2) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `attr_values`
--
-- --------------------------------------------------------
--
-- Table structure for table `banners`
--
CREATE TABLE `banners` (
  `id` int(8) NOT NULL,
  `image` varchar(500) NOT NULL,
  `link` text NOT NULL,
  `order` int(4) NOT NULL,
  `banner_page_id` int(8) NOT NULL,
  `text` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `banners`
--
-- --------------------------------------------------------
--
-- Table structure for table `cart`
--
CREATE TABLE `cart` (
  `id` int(12) NOT NULL,
  `user_id` int(12) NOT NULL,
  `status` int(2) NOT NULL COMMENT '0-in the shopping cart, 1-confirmed, 2-cancelled',
  `session` varchar(255) NOT NULL,
  `address_details` longtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `cart`
--
-- --------------------------------------------------------
--
-- Table structure for table `cart_items`
--
CREATE TABLE `cart_items` (
  `id` int(16) NOT NULL,
  `cart_id` int(12) NOT NULL,
  `product_id` int(12) NOT NULL,
  `size` int(5) NOT NULL,
  `color` int(5) NOT NULL,
  `price_per_unit` varchar(20) CHARACTER SET cp1251 COLLATE cp1251_general_ci NOT NULL,
  `quantity` int(3) NOT NULL,
  `order_time` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `status` tinyint(1) NOT NULL COMMENT '0-hanging in the cart,1-ordered,2-cancelled'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `cart_items`
--
-- --------------------------------------------------------
--
-- Table structure for table `categories`
--
CREATE TABLE `categories` (
  `id` int(12) NOT NULL,
  `name` varchar(255) NOT NULL,
  `safe_name` varchar(255) NOT NULL,
  `parent` int(12) NOT NULL,
  `type` int(1) NOT NULL,
  `order` int(12) NOT NULL,
  `photo` varchar(255) NOT NULL,
  `hidden` int(2) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `categories`
--
-- --------------------------------------------------------
--
-- Table structure for table `cat_attr_rel`
--
CREATE TABLE `cat_attr_rel` (
  `id` int(12) NOT NULL,
  `attr_id` int(12) NOT NULL,
  `cat_id` int(12) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

-- --------------------------------------------------------
--
-- Stand-in structure for view `Doc_Data`
-- (See below for the actual view)
--
CREATE TABLE `Doc_Data` (
`id` bigint(16)
,`OrderNumers` bigint(12)
,`GoodsN` bigint(21)
,`Qty` decimal(10,3)
,`Measure` bigint(11)
,`price` decimal(10,3)
);

-- --------------------------------------------------------
--
-- Stand-in structure for view `Doc_Head`
-- (See below for the actual view)
--
CREATE TABLE `Doc_Head` (
`OrderNumers` int(12)
,`CustomerId` int(5)
,`SkladN` int(1)
,`Operation_Type` int(1)
,`OrderDate` datetime
,`PaymentType` int(2)
,`SumNoDisc` decimal(10,2)
,`DeliveryPrice` decimal(10,2)
,`Discount` decimal(10,0)
,`TotalPrice` decimal(10,2)
,`Voucherid` int(10)
,`Courier` int(2)
,`FullName` varchar(500)
,`Address` longtext
);

-- --------------------------------------------------------
--
-- Table structure for table `econt_cities`
--
CREATE TABLE `econt_cities` (
  `id` int(12) NOT NULL,
  `country` varchar(3) NOT NULL,
  `postcode` varchar(10) NOT NULL,
  `name` varchar(100) NOT NULL,
  `regionName` varchar(100) NOT NULL,
  `nameEn` varchar(100) NOT NULL,
  `city_id` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `econt_cities`
--
-- --------------------------------------------------------
--
-- Table structure for table `favourite_products`
--
CREATE TABLE `favourite_products` (
  `id` int(12) NOT NULL,
  `user_id` int(12) NOT NULL,
  `product_id` int(12) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

--
-- Dumping data for table `favourite_products`
--
-- --------------------------------------------------------
--
-- Table structure for table `firm_details`
--
CREATE TABLE `firm_details` (
  `id` int(12) NOT NULL,
  `user_id` int(12) NOT NULL,
  `name` varchar(255) NOT NULL,
  `eik` varchar(32) NOT NULL,
  `mol` varchar(255) NOT NULL,
  `id_dds` varchar(32) NOT NULL,
  `municipality` varchar(255) NOT NULL,
  `city` varchar(255) NOT NULL,
  `address` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `firm_details`
--
-- --------------------------------------------------------
--
-- Table structure for table `galleries`
--
CREATE TABLE `galleries` (
  `id` int(11) NOT NULL,
  `photo1` varchar(200) NOT NULL,
  `photo2` varchar(200) NOT NULL,
  `title` varchar(200) NOT NULL,
  `products` varchar(500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

-- --------------------------------------------------------
--
-- Table structure for table `general_pages`
--
CREATE TABLE `general_pages` (
  `id` int(8) NOT NULL,
  `label` varchar(50) NOT NULL,
  `text` longtext NOT NULL,
  `type` varchar(50) NOT NULL,
  `url` varchar(200) NOT NULL,
  `order` int(3) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

--
-- Dumping data for table `general_pages`
--
-- --------------------------------------------------------
--
-- Table structure for table `home_page_blocks`
--
CREATE TABLE `home_page_blocks` (
  `id` int(3) NOT NULL,
  `name` varchar(100) NOT NULL,
  `order` int(2) NOT NULL,
  `visible` int(1) NOT NULL DEFAULT 1,
  `type` int(3) NOT NULL,
  `size` int(1) NOT NULL,
  `dimensions` int(1) NOT NULL,
  `gal_type` int(2) NOT NULL,
  `cat` int(10) NOT NULL,
  `gal_type2` int(2) NOT NULL,
  `dimensions2` int(1) NOT NULL,
  `cat2` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `home_page_blocks`
--
-- --------------------------------------------------------
--
-- Table structure for table `last_viewed_products`
--
CREATE TABLE `last_viewed_products` (
  `id` int(12) NOT NULL,
  `session_id` varchar(255) NOT NULL,
  `user_id` int(12) DEFAULT NULL,
  `product_id` int(12) NOT NULL,
  `date_added` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

--
-- Dumping data for table `last_viewed_products`
--
-- --------------------------------------------------------
--
-- Table structure for table `linked_colors`
--
CREATE TABLE `linked_colors` (
  `id` int(6) NOT NULL,
  `name` varchar(32) NOT NULL,
  `linked_colors` varchar(500) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

--
-- Dumping data for table `linked_colors`
--
-- --------------------------------------------------------
--
-- Table structure for table `messages`
--
CREATE TABLE `messages` (
  `id` int(12) NOT NULL,
  `product_id` int(12) NOT NULL,
  `email` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `message` varchar(500) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `status` int(2) DEFAULT 0,
  `date` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

--
-- Dumping data for table `messages`
--
-- --------------------------------------------------------
--
-- Table structure for table `meta_table`
--
CREATE TABLE `meta_table` (
  `id` int(6) NOT NULL,
  `product_id` int(6) NOT NULL,
  `attr_id` int(6) NOT NULL,
  `value` varchar(255) NOT NULL,
  `status` int(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `meta_table`
--
-- --------------------------------------------------------
--
-- Table structure for table `options`
--
CREATE TABLE `options` (
  `id` int(8) NOT NULL,
  `text` text NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------
--
-- Table structure for table `Orak_Counters`
--
CREATE TABLE `Orak_Counters` (
  `Orders` int(11) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

--
-- Dumping data for table `Orak_Counters`
--
-- --------------------------------------------------------
--
-- Table structure for table `orders`
--
CREATE TABLE `orders` (
  `id` int(12) NOT NULL,
  `user_id` int(12) NOT NULL,
  `status` int(1) NOT NULL COMMENT '0:order made; 1: order confirmed; 2: order sent; 3: order done; 4: order cancelled',
  `session` varchar(100) NOT NULL,
  `address_details` longtext NOT NULL,
  `price` varchar(20) NOT NULL,
  `delivery_price` varchar(10) NOT NULL,
  `discount` varchar(10) NOT NULL,
  `total_price` varchar(20) NOT NULL,
  `payment_type` int(2) NOT NULL,
  `courier` int(2) NOT NULL,
  `voucher_id` int(10) NOT NULL,
  `date_time` datetime NOT NULL DEFAULT current_timestamp(),
  `changed` tinyint(1) NOT NULL DEFAULT 0,
  `shipment_number` varchar(128) NOT NULL,
  `shipment_link` text NOT NULL,
  `mail_sent` int(2) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `orders`
--
-- --------------------------------------------------------
--
-- Table structure for table `order_items`
--
CREATE TABLE `order_items` (
  `id` int(16) NOT NULL,
  `order_id` int(12) NOT NULL,
  `product_id` int(12) NOT NULL,
  `size` int(5) NOT NULL,
  `color` int(5) NOT NULL,
  `price_per_unit` varchar(20) NOT NULL,
  `quantity` int(3) NOT NULL,
  `order_time` timestamp NOT NULL DEFAULT current_timestamp(),
  `status` int(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `order_items`
--
-- --------------------------------------------------------
--
-- Table structure for table `products`
--
CREATE TABLE `products` (
  `id` int(12) NOT NULL,
  `sku` varchar(255) NOT NULL,
  `title` text NOT NULL,
  `description` longtext DEFAULT NULL,
  `price` varchar(60) NOT NULL,
  `discount_price` varchar(60) NOT NULL,
  `status` int(2) NOT NULL DEFAULT 1,
  `weight` double(10,3) NOT NULL,
  `model_description` text NOT NULL,
  `code` varchar(255) NOT NULL,
  `xxl` int(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `products`
--
-- --------------------------------------------------------
--
-- Table structure for table `product_cat_rel`
--
CREATE TABLE `product_cat_rel` (
  `id` int(6) NOT NULL,
  `product_id` int(12) NOT NULL,
  `cat_id` int(12) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `product_cat_rel`
--
-- --------------------------------------------------------
--
-- Table structure for table `product_photos`
--
CREATE TABLE `product_photos` (
  `id` int(12) NOT NULL,
  `product_id` int(12) NOT NULL,
  `photo_name` varchar(255) NOT NULL,
  `main_photo` int(1) NOT NULL,
  `order` int(8) NOT NULL,
  `color` int(6) NOT NULL,
  `title` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `product_photos`
--
-- --------------------------------------------------------
--
-- Table structure for table `product_quantities`
--
CREATE TABLE `product_quantities` (
  `id` int(12) NOT NULL,
  `product_id` int(12) NOT NULL,
  `color` int(3) NOT NULL,
  `size` int(3) NOT NULL,
  `quantity` int(8) NOT NULL,
  `price` varchar(40) NOT NULL,
  `discount_price` varchar(40) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `product_quantities`
--
-- --------------------------------------------------------
--
-- Table structure for table `quick_orders`
--
CREATE TABLE `quick_orders` (
  `id` int(8) NOT NULL,
  `user_id` int(8) NOT NULL,
  `product_id` int(8) NOT NULL,
  `size` int(6) NOT NULL,
  `color` int(6) NOT NULL,
  `quantity` int(6) NOT NULL,
  `email` varchar(255) NOT NULL,
  `phone` varchar(255) NOT NULL,
  `status` int(2) NOT NULL,
  `order_timestamp` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

-- --------------------------------------------------------
--
-- Table structure for table `sets`
--
CREATE TABLE `sets` (
  `id` int(11) NOT NULL,
  `photo1` varchar(200) NOT NULL,
  `photo2` varchar(200) NOT NULL,
  `text` varchar(200) NOT NULL,
  `product_ids` varchar(500) NOT NULL,
  `order` int(6) NOT NULL,
  `type` int(3) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `sets`
--
-- --------------------------------------------------------
--
-- Table structure for table `settings`
--
CREATE TABLE `settings` (
  `id` int(9) NOT NULL,
  `key` varchar(50) NOT NULL,
  `value` longtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `settings`
--
-- --------------------------------------------------------
--
-- Table structure for table `sizes_template`
--
CREATE TABLE `sizes_template` (
  `id` int(6) NOT NULL,
  `name` varchar(128) NOT NULL,
  `param1` varchar(128) NOT NULL,
  `param2` varchar(128) NOT NULL,
  `param3` varchar(128) NOT NULL,
  `param4` varchar(128) NOT NULL,
  `param5` varchar(128) NOT NULL,
  `param6` varchar(128) NOT NULL,
  `param7` varchar(128) NOT NULL,
  `param8` varchar(128) NOT NULL,
  `image` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `sizes_template`
--
-- --------------------------------------------------------
--
-- Table structure for table `sizes_template_product`
--
CREATE TABLE `sizes_template_product` (
  `id` int(12) NOT NULL,
  `product_id` int(12) NOT NULL,
  `template_id` int(5) NOT NULL,
  `param` int(2) NOT NULL,
  `size_id` varchar(5) NOT NULL,
  `value` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `sizes_template_product`
--
-- --------------------------------------------------------
--
-- Table structure for table `slides`
--
CREATE TABLE `slides` (
  `id` int(8) NOT NULL,
  `image` varchar(500) NOT NULL,
  `link` varchar(500) NOT NULL,
  `order` int(4) NOT NULL,
  `type` int(3) NOT NULL,
  `title` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

--
-- Dumping data for table `slides`
--
-- --------------------------------------------------------
--
-- Table structure for table `software_measures`
--
CREATE TABLE `software_measures` (
  `id` int(10) NOT NULL,
  `external_id` int(10) NOT NULL,
  `size` varchar(100) NOT NULL,
  `color` varchar(100) NOT NULL,
  `color_id` int(6) NOT NULL,
  `size_id` int(6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `software_measures`
--
-- --------------------------------------------------------
--
-- Table structure for table `speditors`
--
CREATE TABLE `speditors` (
  `id` int(3) NOT NULL,
  `name` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `speditors`
--
-- --------------------------------------------------------
--
-- Table structure for table `translations`
--
CREATE TABLE `translations` (
  `id` int(10) NOT NULL,
  `type` varchar(50) NOT NULL,
  `relation_id` int(12) NOT NULL,
  `lang` varchar(3) NOT NULL,
  `text` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `translations`
--
-- --------------------------------------------------------
--
-- Table structure for table `unique_vouchers`
--
CREATE TABLE `unique_vouchers` (
  `id` int(12) NOT NULL,
  `text` varchar(80) NOT NULL,
  `used` int(1) NOT NULL,
  `created` datetime NOT NULL DEFAULT current_timestamp(),
  `user_phone` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `unique_vouchers`
--
-- --------------------------------------------------------
--
-- Table structure for table `users`
--
CREATE TABLE `users` (
  `id` int(3) NOT NULL,
  `username` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(32) NOT NULL,
  `full_name` varchar(500) NOT NULL,
  `phone` varchar(100) NOT NULL,
  `reg_date` timestamp NOT NULL DEFAULT current_timestamp(),
  `city` longtext DEFAULT NULL,
  `post_code` int(6) DEFAULT NULL,
  `address` longtext DEFAULT NULL,
  `approved` int(2) NOT NULL,
  `hash` varchar(32) NOT NULL,
  `reset_pass_hash` varchar(32) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `users`
--
-- --------------------------------------------------------
--
-- Table structure for table `vouchers`
--
CREATE TABLE `vouchers` (
  `id` int(20) NOT NULL,
  `name` varchar(20) NOT NULL,
  `type` int(2) NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `discount` varchar(20) NOT NULL,
  `discount_type` int(2) NOT NULL,
  `order_min_price` int(5) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `vouchers`
--
--
-- Indexes for dumped tables
--
--
-- Indexes for table `address`
--
ALTER TABLE `address`
--
-- Indexes for table `admin_users`
--
ALTER TABLE `admin_users`
--
-- Indexes for table `attributes`
--
ALTER TABLE `attributes`
--
-- Indexes for table `attr_values`
--
ALTER TABLE `attr_values`
--
-- Indexes for table `banners`
--
ALTER TABLE `banners`
--
-- Indexes for table `cart`
--
ALTER TABLE `cart`
--
-- Indexes for table `cart_items`
--
ALTER TABLE `cart_items`
--
-- Indexes for table `categories`
--
ALTER TABLE `categories`
--
-- Indexes for table `cat_attr_rel`
--
ALTER TABLE `cat_attr_rel`
--
-- Indexes for table `econt_cities`
--
ALTER TABLE `econt_cities`
--
-- Indexes for table `favourite_products`
--
ALTER TABLE `favourite_products`
--
-- Indexes for table `firm_details`
--
ALTER TABLE `firm_details`
--
-- Indexes for table `general_pages`
--
ALTER TABLE `general_pages`
--
-- Indexes for table `home_page_blocks`
--
ALTER TABLE `home_page_blocks`
--
-- Indexes for table `last_viewed_products`
--
ALTER TABLE `last_viewed_products`
--
-- Indexes for table `linked_colors`
--
ALTER TABLE `linked_colors`
--
-- Indexes for table `messages`
--
ALTER TABLE `messages`
--
-- Indexes for table `meta_table`
--
ALTER TABLE `meta_table`
--
-- Indexes for table `options`
--
ALTER TABLE `options`
--
-- Indexes for table `orders`
--
ALTER TABLE `orders`
--
-- Indexes for table `order_items`
--
ALTER TABLE `order_items`
--
-- Indexes for table `products`
--
ALTER TABLE `products`
--
-- Indexes for table `product_cat_rel`
--
ALTER TABLE `product_cat_rel`
--
-- Indexes for table `product_photos`
--
ALTER TABLE `product_photos`
--
-- Indexes for table `product_quantities`
--
ALTER TABLE `product_quantities`
--
-- Indexes for table `quick_orders`
--
ALTER TABLE `quick_orders`
--
-- Indexes for table `sets`
--
ALTER TABLE `sets`
--
-- Indexes for table `settings`
--
ALTER TABLE `settings`
--
-- Indexes for table `sizes_template`
--
ALTER TABLE `sizes_template`
--
-- Indexes for table `sizes_template_product`
--
ALTER TABLE `sizes_template_product`
--
-- Indexes for table `slides`
--
ALTER TABLE `slides`
--
-- Indexes for table `software_measures`
--
ALTER TABLE `software_measures`
--
-- Indexes for table `speditors`
--
ALTER TABLE `speditors`
--
-- Indexes for table `translations`
--
ALTER TABLE `translations`
--
-- Indexes for table `unique_vouchers`
--
ALTER TABLE `unique_vouchers`
--
-- Indexes for table `users`
--
ALTER TABLE `users`
--
-- Indexes for table `vouchers`
--
ALTER TABLE `vouchers`
--
-- AUTO_INCREMENT for dumped tables
--
--
-- AUTO_INCREMENT for table `address`
--
ALTER TABLE `address`
--
-- AUTO_INCREMENT for table `admin_users`
--
ALTER TABLE `admin_users`
--
-- AUTO_INCREMENT for table `attributes`
--
ALTER TABLE `attributes`
--
-- AUTO_INCREMENT for table `attr_values`
--
ALTER TABLE `attr_values`
--
-- AUTO_INCREMENT for table `banners`
--
ALTER TABLE `banners`
--
-- AUTO_INCREMENT for table `cart`
--
ALTER TABLE `cart`
--
-- AUTO_INCREMENT for table `cart_items`
--
ALTER TABLE `cart_items`
--
-- AUTO_INCREMENT for table `categories`
--
ALTER TABLE `categories`
--
-- AUTO_INCREMENT for table `cat_attr_rel`
--
ALTER TABLE `cat_attr_rel`
--
-- AUTO_INCREMENT for table `econt_cities`
--
ALTER TABLE `econt_cities`
--
-- AUTO_INCREMENT for table `favourite_products`
--
ALTER TABLE `favourite_products`
--
-- AUTO_INCREMENT for table `firm_details`
--
ALTER TABLE `firm_details`
--
-- AUTO_INCREMENT for table `general_pages`
--
ALTER TABLE `general_pages`
--
-- AUTO_INCREMENT for table `home_page_blocks`
--
ALTER TABLE `home_page_blocks`
--
-- AUTO_INCREMENT for table `last_viewed_products`
--
ALTER TABLE `last_viewed_products`
--
-- AUTO_INCREMENT for table `linked_colors`
--
ALTER TABLE `linked_colors`
--
-- AUTO_INCREMENT for table `messages`
--
ALTER TABLE `messages`
--
-- AUTO_INCREMENT for table `meta_table`
--
ALTER TABLE `meta_table`
--
-- AUTO_INCREMENT for table `options`
--
ALTER TABLE `options`
--
-- AUTO_INCREMENT for table `orders`
--
ALTER TABLE `orders`
--
-- AUTO_INCREMENT for table `order_items`
--
ALTER TABLE `order_items`
--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
--
-- AUTO_INCREMENT for table `product_cat_rel`
--
ALTER TABLE `product_cat_rel`
--
-- AUTO_INCREMENT for table `product_photos`
--
ALTER TABLE `product_photos`
--
-- AUTO_INCREMENT for table `product_quantities`
--
ALTER TABLE `product_quantities`
--
-- AUTO_INCREMENT for table `quick_orders`
--
ALTER TABLE `quick_orders`
--
-- AUTO_INCREMENT for table `sets`
--
ALTER TABLE `sets`
--
-- AUTO_INCREMENT for table `settings`
--
ALTER TABLE `settings`
--
-- AUTO_INCREMENT for table `sizes_template`
--
ALTER TABLE `sizes_template`
--
-- AUTO_INCREMENT for table `sizes_template_product`
--
ALTER TABLE `sizes_template_product`
--
-- AUTO_INCREMENT for table `slides`
--
ALTER TABLE `slides`
--
-- AUTO_INCREMENT for table `software_measures`
--
ALTER TABLE `software_measures`
--
-- AUTO_INCREMENT for table `speditors`
--
ALTER TABLE `speditors`
--
-- AUTO_INCREMENT for table `translations`
--
ALTER TABLE `translations`
--
-- AUTO_INCREMENT for table `unique_vouchers`
--
ALTER TABLE `unique_vouchers`
--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
--
-- AUTO_INCREMENT for table `vouchers`
--
ALTER TABLE `vouchers`
-- --------------------------------------------------------
--
-- Structure for view `Doc_Data`
--
DROP TABLE IF EXISTS `Doc_Data`;
-- --------------------------------------------------------
--
-- Structure for view `Doc_Head`
--
DROP TABLE IF EXISTS `Doc_Head`;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
